{% set name = "pygnssutils" %}
{% set version = "1.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygnssutils-{{ version }}.tar.gz
  sha256: 161d527d794e6bc93ad1a7ab0eea63ca6fb1f602ffc3c7a7e5b24ebd50c74145
build:
  entry_points:
    - gnssdump = pygnssutils.gnssdump_cli:main
    - gnssserver = pygnssutils.gnssserver_cli:main
    - gnssntripclient = pygnssutils.gnssntripclient_cli:main
    - gnssmqttclient = pygnssutils.gnssmqttclient_cli:main
    - ubxsetrate = pygnssutils.ubxsetrate:main
    - ubxsave = pygnssutils.ubxsave:main
    - ubxload = pygnssutils.ubxload:main
    - ubxsimulator = pygnssutils.ubxsimulator_cli:main
    - ubxcompare = pygnssutils.ubxcompare:main

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - certifi >=2024.0.0
    - python >=3.8
    - paho-mqtt >=1.6.1
    - pyserial >=3.5
    - pyspartn >=1.0.2
    - pyubx2 >=1.2.43

test:
  imports:
    - pygnssutils
  commands:
    - pip check
    - gnssdump --help
    - gnssserver --help
    - gnssntripclient --help
    - gnssmqttclient --help
    - ubxsetrate --help
    - ubxsave --help
    - ubxload --help
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pygnssutils
  description: Python GNSS CLI utility library.
  summary: Python GNSS CLI utility library.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pygnssutils
  dev_url: https://github.com/semuconsulting/pygnssutils

extra:
  recipe-maintainers:
    - semuadmin
