{% set name = "pygnssutils" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygnssutils-{{ version }}.tar.gz
  sha256: 48f3d8b5d2444b5076dfe57881e5d0cc008a2413ec4e38ac6623b305e5fba937
build:
  entry_points:
    - gnssstreamer = pygnssutils.gnssstreamer_cli:main
    - gnssserver = pygnssutils.gnssserver_cli:main
    - gnssntripclient = pygnssutils.gnssntripclient_cli:main
    - gnssmqttclient = pygnssutils.gnssmqttclient_cli:main

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - certifi >=2024.0.0
    - paho-mqtt >=1.6.1
    - pyserial >=3.5
    - pyspartn >=1.0.5
    - pyubx2 >=1.2.48
    - pyubxutils >=1.0.2

test:
  imports:
    - pygnssutils
  commands:
    - pip check
    - gnssstreamer --help
    - gnssserver --help
    - gnssntripclient --help
    - gnssmqttclient --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/semuconsulting/pygnssutils
  description: Python GNSS CLI utility library.
  summary: Python GNSS CLI utility library.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pygnssutils
  dev_url: https://github.com/semuconsulting/pygnssutils

extra:
  recipe-maintainers:
    - semuadmin
