{% set name = "pygnssutils" %}
{% set version = "1.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygnssutils-{{ version }}.tar.gz
  sha256: 80e19131ff7d584baa8cba9828ba48b0fc788a1e61c3f8fff414b5537768703d
build:
  entry_points:
    - gnssdump = pygnssutils.gnssdump:main
    - gnssserver = pygnssutils.gnssserver:main
    - gnssntripclient = pygnssutils.gnssntripclient:main
    - gnssmqttclient = pygnssutils.gnssmqttclient:main
    - ubxsetrate = pygnssutils.ubxsetrate:main
    - ubxsave = pygnssutils.ubxsave:main
    - ubxload = pygnssutils.ubxload:main
    - ubxsimulator = pygnssutils.ubxsimulator:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - certifi >=2024.0.0
    - python >=3.8
    - paho-mqtt >=2.0.0
    - pyserial >=3.5
    - pyspartn >=1.0.0
    - pyubx2 >=1.2.40

test:
  imports:
    - pygnssutils
  commands:
    - pip check
    - gnssdump --help
    - gnssserver --help
    - gnssntripclient --help
    - gnssmqttclient --help
    - ubxsetrate --help
    - ubxsave --help
    - ubxload --help
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pygnssutils
  description: Python GNSS CLI utility library.
  summary: Python GNSS CLI utility library.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pygnssutils
  dev_url: https://github.com/semuconsulting/pygnssutils

extra:
  recipe-maintainers:
    - semuadmin
